sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=client/src,server/src

sonar.exclusions=**/node_modules/**,client/dist/**,**/coverage/**,client/src/**/__tests__/**,client/src/**/*.test.js,client/src/**/*.test.jsx,client/src/**/*.spec.js,client/src/**/*.spec.jsx

sonar.tests=client/src,server/tests

sonar.test.inclusions=client/src/**/__tests__/**,client/src/**/*.test.js,client/src/**/*.test.jsx,client/src/**/*.spec.js,client/src/**/*.spec.jsx,server/tests/**/*.js

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
